--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/jasper/Pictures/wallpapers/wallpaper.jpg"

-- Special
background="#3b1b22"
foreground="#ddd2de"
cursor="#ddd2de"

-- Colors
color0="#3b1b22"
color1="#6C5DA4"
color2="#4E76C5"
color3="#9E6198"
color4="#C96F89"
color5="#4B92C6"
color6="#BC9FB7"
color7="#ddd2de"
color8="#9a939b"
color9="#6C5DA4"
color10="#4E76C5"
color11="#9E6198"
color12="#C96F89"
color13="#4B92C6"
color14="#BC9FB7"
color15="#ddd2de"
