# Shell variables
# Generated by 'wal'
wallpaper='/home/jasper/Pictures/wallpapers/wallpaper.jpg'

# Special
background='#3b1b22'
foreground='#ddd2de'
cursor='#ddd2de'

# Colors
color0='#3b1b22'
color1='#6C5DA4'
color2='#4E76C5'
color3='#9E6198'
color4='#C96F89'
color5='#4B92C6'
color6='#BC9FB7'
color7='#ddd2de'
color8='#9a939b'
color9='#6C5DA4'
color10='#4E76C5'
color11='#9E6198'
color12='#C96F89'
color13='#4B92C6'
color14='#BC9FB7'
color15='#ddd2de'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
