#! /bin/sh
bspc rule -r "*"

monmiddle=HDMI-0
monright=DVI-D-0

xrandr --output $monmiddle --primary  
xrandr --output $monright --right-of $monmiddle


borderbase=5
padding=$borderbase

gaps="30"

bspc config border_width        2
bspc config window_gap          $gaps

#bspc config border_width=$borderbasei

bspc monitor $monright -d  1 2 3 4 5  
bspc monitor $monmiddle -d  6 7 8 9 0   

wallpaper=${HOME}/Pictures/wallpapers/wallpaper.jpg
feh --bg-scale $wallpaper

bspc config normal_border_color 	"$color11"
bspc config active_border_color 	"$color2"
bspc config focused_border_color 	"$color15"
bspc config presel_feedback_color	"$color1"
bspc config split_ratio          	1.1
bspc config borderless_monocle   	true
bspc config gapless_monocle       	true
bspc config pointer_follows_monitor	true 
bspc config ignore_ewmh_focus		true

bspc config top_padding 35
override-redirect = true

sxhkd &
#required services

bspc rule -a *:*
bspc rule -a firefox desktop="^6" state=tiled
bspc rule -a libreoffice-startcenter  desktop='^1' state=tiled 
bspc rule -a "VirtualBox Manager" desktop='^2' state=tiled 
bspc rule -a Vmware desktop='^2'
bspc rule -a Spotify desktop='^4'state=tiled
#bspc rule -a Steam desktop='^5' 
bspc rule -a urxvt desktop="^3" state=tiled
bspc rule -a urxvt:ranger desktop="^4" state=tiled
bspc rule -a lutris desktop='^9' state=tiled 
bspc rule -a emulationstation deskrop='^8' state=fullscreen
bspc rule -a Kodi desktop='^7' state=fullscreen
bspc rule -a Gimp desktop='^0' state=tiled
bspc rule -a "origin.exe" state=floating
bspc rule -a wine:Wine state=floating

bspc config external_rules_command "$(which ~/.config/bspwm/external_rules)"

source "${HOME}/.cache/wal/colors.sh"


source "${HOME}/.cache/wal/colors.sh"


if pidof -s firefox 
then echo "all good"
else
~/autostart.sh
fi

picom --experimental-backends &

transon

wal -R

tranmission-daemon

