#!/usr/bin/env bash

bspc config automatic_scheme longest_side

wid=$1
class=$2
instance=$3

if xprop -id $wid | grep "_NET_WM_WINDOW_TYPE_DIALOG";then
	echo "state=floating"
elif [ "$instance" = Steam ] ; then
	title=$(xprop -id $wid | grep "^WM_NAME" | awk -F " = " '{print $2}')
	case "$title" in
		*" - Steam"*|*"Product Activation"*|*Settings*)
			echo "state=floating"
			echo "center=on"
			;;
		*)
			echo "state=tiled"
	esac
elif [ "$instance" = gimp ]; then
	title=$(xprop -id $wid | grep "^WM_NAME" | awk -F " = " '{print $2}')
	case "$title" in
		*"GIMP Startup"*)
			echo "state=floating"
			echo "center=on"
			;;
		*)
			echo "state=tiled"
	esac
fi

